### ISSUE TITLE
dziwne rzeczy w kodzie

### ISSUE THREAD

**Issue by ziuniecki** [krzysztof-grzybek/aframe-position-spherical-component#1]
https://github.com/krzysztof-grzybek/aframe-position-spherical-component/blob/a09de4a5f2dfcbda7e727528f8f9aab2d3e842a5/index.js#L1

Nie wiem dlaczego takie rzeczy się pojawiły na repo

**Comment by krzysztof-grzybek** [comment]
To już po fixie, wcześniej było console.log('dupa')

**Comment by ziuniecki** [comment]
yhym w takim razie w porządku isiuł do zamknięcia
